# Generated by Django 4.2.8 on 2023-12-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorders',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
