# Generated by Django 4.2.8 on 2023-12-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_remove_orders_adress_orders_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
    ]
