# Generated by Django 4.2.8 on 2024-01-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_orders_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catogory',
            field=models.CharField(default=3456, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
